heat_template_version: 2016-04-08

parameters:

    index:
        type: number
        label: Server index
        description: Index into the lists of VM names

    vmNames:
        type: comma_delimited_list
        label: VM Names
        description: List of SD VM names

    image:
        type: string
        label: VM image
        description: The image for the SD VM

    flavor:
        type: string
        label: VM flavor
        description: The flavor that defines the VM size for the SD VM


    serverGroup: 
        type: string
        label: SD server group
        description: The server group that is used by SD servers

    availabilityZone:
        type: string
        label: Availability zone
        description: The availability zone into which SD VMs should be placed    

    securityGroup:
        type: string
        label: Security Group
        description: Security group used by servers

    privateNetwork:
        type: string
        label: private Network 
        description: private network for servers

resources:
            
    #Port Creation
    privatePort: 
        type: OS::Neutron::Port
        properties:
            name: { list_join: ['-', [{get_param: [vmNames, get_param: index]}, "private"]]}
            network: { get_param: privateNetwork }
            security_groups:
                - { get_param: securityGroup }

    # Create a single server
    server:
        type: OS::Nova::Server
        properties:
            image: { get_param: image }
            flavor: { get_param: flavor }
            name:  { get_param: [ vmNames, get_param: index ] }
            availability_zone: { get_param: availabilityZone }
            scheduler_hints: { group: { get_param: serverGroup } }
            config_drive: true
            networks:
                - port: { get_resource: privatePort }

