parameters:
    # Name or ID of Glance VM image to deploy
    # For example:
    #   imageID: Unica_Gen_2VNIC_Cirros_0.3.4
    imageID: Unica_Gen_2VNIC_Cirros_0.3.4

    # The Avalibility Zone where new VM instances should be deployed
    AZ: TypeB_01

    # Comma separated list of names for new VM instances.
    # For example:
    # vmNames: 'vm1,vm2,vm3,vm4'
    vmNames: 'vm_1,vm2'

    # Hypervisor affinity rule to apply for HA-paired VMs.
    # affinity - the SD VMs will be placed on the same physical server
    # anti-affinity - the SD VMs will be placed on different physical servers
    Affinity: anti-affinity

    #Virtual network Name
    vn_name: private_HA_network

    #Virtual subnet name
    private_subnet_name: private_HA_subnet

    #Segmentation id for vxlan ID
    segmentation_id: 1243

    #CIDR for subnet
    subnet_vn_CIDR: 192.168.1.0/24

    #Subnet Gateway
    gateway_vn: 192.168.1.1