heat_template_version: 2015-04-30

description:
  Template to define new SecurityGroup in a HOT Package


resources:
  
  mav_tel_secgroup:
    type: OS::Neutron::SecurityGroup
    properties:
      description: Add security group rules for solution
      name: CPRIETO_securitygroup_TEST
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          protocol: udp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: tcp
        - remote_ip_prefix: 0.0.0.0/0
          protocol: icmp
        - remote_ip_prefix: "::/0"
          ethertype: IPv6
          protocol: udp 
        - remote_ip_prefix: "::/0"
          ethertype: IPv6
          protocol: tcp 
        - remote_ip_prefix: "::/0"
          ethertype: IPv6
          protocol: icmp 